[[constraint]]
  name = "github.com/graphql-go/graphql"
  version = "0.7.6"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true
